### ISSUE TITLE
Taskbar Labels minimum width ignored

### ISSUE THREAD

**Issue by MamiyaOtaru** [ramensoftware/windhawk-mods#1097]
Since 1.3 taskbar labels do not shrink past a certain point and instead extra windows go to the overflow area, exactly the same as if Taskbar Labels mod wasn't enabled at all.  Being able to fit more icons/labels on the taskbar is the whole reason I use this mod but it isn't affecting minimum width at all now.  

It does seem to cause the overflow area to be blank sometimes (when it shouldn't be) so some icons are sometimes just gone.  And it crashes a bunch :(  Will add logs when I get them (just enabled), but my main issue is with the "Minimum taskbar item width setting" being ignored

Win 11 23H2 build 22631.4317

**Comment by m417z** [comment]
I believe that the option stopped working after a recent Windows update. I'll take a closer look at it soon.

Regarding the crashes, I'm not aware of such problems with the mod. Please open a new issue and post a crash dump. You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by m417z** [comment]
Fixed in version 1.3.2.

**Comment by Marshall-Brooks** [comment]
Thank you! It is working better, but it still is not "fixed" in 1.3.2. For example, I set a minimum width of "4". I still see the icon (which I think is 22 px) and the first letter and the beginning of the ellipsis (i.e. A.) when it starts going to overflow.
![image](https://github.com/user-attachments/assets/7fdcf2d5-06ba-4793-8c0c-0285837672fe)

That's fine for my external monitor, but not for my laptop internal display.

(I don't necessarily want it to go all the way down to 4 pixels wide, but I'd like it to all least go the the width that I get with "No labels, don't combine buttons.)

Also - I'm sure this would be more difficult to implement, but what I really want would be a setttings for "Don't overflow, show labels, don't combine unless necessary." where it would reduce the icons to my minimum width and then combine them so it didn't go to the overflow menu - but I think that is asking quite a lot ...

**Comment by Marshall-Brooks** [comment]
Also - for me, Explorer seems to crash when the taskbar goes to overflow. Not sure if that is caused by the mod or not, but it's one reason I would prefer to disable overflow altogether ...

**Comment by Marshall-Brooks** [comment]
_Also - I'm sure this would be more difficult to implement, but what I really want would be a setttings for "Don't overflow, show labels, don't combine unless necessary." where it would reduce the icons to my minimum width and then combine them so it didn't go to the overflow menu - but I think that is asking quite a lot ..._

Disregard - There is a Windows setting for "Combine Taskbar Buttons and Hide Labels - When the taskbar is full" and that seems to work with the mod and do what I want it to do.

Just would like the minimum icon width smaller on my laptop display.

**Comment by m417z** [comment]
> It is working better, but it still is not "fixed" in 1.3.2

First of all, this issue says: "Taskbar Labels minimum width ignored". This is fixed. Any other issues or imperfections about this option or the mod in general are separate issues.

> I set a minimum width of "4". I still see the icon (which I think is 22 px) and the first letter and the beginning of the ellipsis (i.e. A.) when it starts going to overflow

The mod limits the value to 44px. I don't remember why exactly I set this limit. It indeed makes little sense to set a value smaller than that with the default icon size, but in your case it might make sense. I'll remove this limit in the next update. For now, you can fork the mod and remove this block:
```cpp
        if (minimumTaskbarItemWidth < 44) {
            minimumTaskbarItemWidth = 44;
            Wh_Log(L"minimumTaskbarItemWidth too small, using %d",
                   minimumTaskbarItemWidth);
        }
```

> Also - for me, Explorer seems to crash when the taskbar goes to overflow. Not sure if that is caused by the mod or not, but it's one reason I would prefer to disable overflow altogether ...

Might be this issue: https://github.com/ramensoftware/windhawk-mods/issues/478.

**Comment by Marshall-Brooks** [comment]
Tried to create a fork and I'm getting a compile error "Failed to parse settings - not a valid YAML array".  I'll probably just wait for 1.3.3. Explorer crash is likely the $478 link you posted.

**Comment by Marshall-Brooks** [comment]
Minor issue, but the Running Indicator Style for Taskbar Labels for Windows 11 overrides the Windows 11 Taskbar Styler setting for taskbar:TaskListLabeledButtonPanel@RunningIndicatorStates > Rectangle#RunningIndicator - Visibility=Collapsed.

I set it to be under the icon on the left, and I have the icon basically the same height as the taskbar, so it is barely visible, but ...

Would be nice to have a setting in Taskbar Labels for Running Indicator - Hidden and then I could remove the Taskbar Styler setting.

**Comment by MamiyaOtaru** [comment]
thanks for the fix.  the crashes did seem to be related to overflow, so they are for sure less frequent now that I am not overflowing as fast.  It can still happen of course (particularly when I unplug two monitors) so I'll watch for it and follow your instructions for another report if any more crashes crop up.  TY!
