### ISSUE TITLE
Taskbar classic context menu mod breaks the Win10 task bar

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk-mods#1101]
When enabling "Taskbar classic context menu" mod and regardless of the options set, the Win10 taskbar (under Win11 23H2) gets black background:
![изображение](https://github.com/user-attachments/assets/0e8af679-4cc2-4810-bc10-564b1cd1e3b0)

Mod author: @m417z .

**Comment by Anixx** [comment]
Is there a hope this will be fixed? I just hope I will be able to get rid of 7+TT and move entirely to Windhawk.

**Comment by m417z** [comment]
Is that with the "Customize the old taskbar on Windows 11" option enabled? That's a surprising bug, the mod doesn't do much, it just makes explorer think that Shift is pressed.

I don't plan on setting up an environment with a Win10 classic taskbar to test it, but if you can figure out where the problem is, perhaps we can come up with a fix. You can fork the code and remove some of it to see if it helps. For example, you can start by replacing the `HookWin10TaskbarSymbols` function with and see if it changes anything:
```cpp
bool HookWin10TaskbarSymbols() {
    return true;
}
```

**Comment by Anixx** [comment]
With this replacement, the taskbar does not get shown.

**Comment by Anixx** [comment]
With the original mod also, the taskbar does not appear at hard Explorer restart, the black background appears only if to enable mod with running Explorer. If to restart Explorer, the taskbar does not appear.

**Comment by Anixx** [comment]
With the setting "Customize the old taskbar on Windows 11" enabled, the taskbar does not appear at all, either with soft or hard Explorer restart.

**Comment by Anixx** [comment]
Well, now I got the mod working, but only the forked version. When I enable the original mod, it does not. The settings are the same. The diff shows no significant difference. I wonder, why thic can be the case.

**Comment by m417z** [comment]
Are you using ExplorerPatcher? If not, and if you're using the Win10 taskbar on Win11, you should enable the "Customize the old taskbar on Windows 11" option, otherwise the mod won't work for sure.

If it crashes for you, please attach a crash dump. You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value 2
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by m417z** [comment]
That makes sense, the mod inverts the Shift button state, and the tweaker inverts it back.

**Comment by Anixx** [comment]
I am again getting the black background after Explorer restart... So maybe, the issue is not over.

**Comment by Anixx** [comment]
Oh it seems it is because of the other mod "disable groupping on the taskbar". It also needs a setting for the old taskbar. Do not you consider to enable this setting in all these mods by default? I think, it does not affect anything when the new taskbar is used.

**Comment by m417z** [comment]
Some of these mods detect ExplorerPatcher and use the Win10 mode automatically. For some mods, such as "disable grouping", I plan on adding this functionality, but didn't get to it yet. For other methods of running the Win10 taskbar on Win11, I don't plan on working on automatic detection.

**Comment by Anixx** [comment]
I meant not the adding of any functionality but just enabling the option by default. Will if disrupt something if enabled?

**Comment by m417z** [comment]
Trying to customize both means requiring to download symbols for both explorer.exe and taskbar.dll, which is unnecessary for most users. Although Windhawk now uses the symbol cache server, cache isn't always available. And I'm not sure it will help in your case, as it looks like some part of the attempt to customize the Win11 taskbar causes problems for you.

**Comment by Anixx** [comment]
No. The issue as it looks like now was in the need to enable this option "Customize the old taskbar on Windows 11" simultaniously in 3 mods: "Disable Taskbar Thumbnails", "Disable grouping on the taskbar" and "Taskbar classic context menu". If at least one of them does not have this option enabled, the taskbar has a black background, or even worse, Explorer does not start (no taskbar and desktop is shown).

**Comment by m417z** [comment]
I understand. If the mods would have detection for ExplorerPatcher implemented, it'd switch to the Win10 taskbar flow, and won't try to customize the Win11 taskbar, which is probably what causes issues for you. But they don't, so you need to handle that manually.

In fact, the auto-detection for ExplorerPatcher only works with the EP taskbar, not with the native Win10 taskbar (even with ExplorerPatcher). So I'm not sure it'd help you.

**Comment by Anixx** [comment]
The Win10 taskbar can be enabled on Win11 21H2-23H2 with a registry key (or a registry query hook as it is done by a mod "Windows 10 taskbar on Windows 11"). So, running EP is not really needed for having the Win10 taskbar enabled.
Also, one can run the taskbar from Win10 under Win11 24H2, for which there is also a mod. So, checking for EP is not a solution anyway.

**Comment by m417z** [comment]
Yes, I know. The specific detection I implemented only works for the EP taskbar implementation.

**Comment by Anixx** [comment]
Well, for now the only 7+TT functionality that I use that remains still not ported to Windhawk is the tray icons spaccing. Also, "hide start button", but it is less important.
