### ISSUE TITLE
[Vertical Taskbar for Windows 11] Start Menu opens in incorrect location with dual-screen setup

### ISSUE THREAD

**Issue by jay33721** [ramensoftware/windhawk-mods#1363]
@m417z 

I have a dual-screen setup, with the taskbar set to be on the left on my primary monitor and on the right on my secondary monitor. The Start Menu opens on the left-hand side of the secondary monitor and draws under the taskbar on the primary monitor. I'm on Windows 11 24H2 (26100.2605). This happens even with no other mods active.

Primary Monitor:
![Screenshot 2024-12-18 100318](https://github.com/user-attachments/assets/de97449c-2619-4683-98af-90a6ea4d05c6)

Secondary Monitor:
![Screenshot 2024-12-18 100339](https://github.com/user-attachments/assets/c7e6c140-679e-4a1d-b585-9c9acaf372ac)

Here is the log of me opening and closing the Start Menu on each monitor (I don't know what else would be helpful to put as a log):
```
10:14:04.846 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:05.069 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:05.147 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:05.147 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:05.148 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:05.156 24404 explorer.exe  [WH] [taskbar-vertical] [1784:TaskListButton_UpdateVisualStates_Hook]: >
10:14:05.156 24404 explorer.exe  [WH] [taskbar-vertical] [1180:RepeatButton_Width_Hook]: >
10:14:05.157 24404 explorer.exe  [WH] [taskbar-vertical] [1784:TaskListButton_UpdateVisualStates_Hook]: >
10:14:05.157 24404 explorer.exe  [WH] [taskbar-vertical] [1180:RepeatButton_Width_Hook]: >
10:14:05.165 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:06.002 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:06.065 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:06.066 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:06.067 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:06.070 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:06.079 24404 explorer.exe  [WH] [taskbar-vertical] [1784:TaskListButton_UpdateVisualStates_Hook]: >
10:14:06.079 24404 explorer.exe  [WH] [taskbar-vertical] [1180:RepeatButton_Width_Hook]: >
10:14:06.080 24404 explorer.exe  [WH] [taskbar-vertical] [1784:TaskListButton_UpdateVisualStates_Hook]: >
10:14:06.080 24404 explorer.exe  [WH] [taskbar-vertical] [1180:RepeatButton_Width_Hook]: >
10:14:07.277 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.277 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.744 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.748 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.749 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.815 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.816 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.816 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.821 10660 StartMenuExperienceHost.exe  [WH] [taskbar-vertical] [2853:SetWindowPos_Hook]: 00050266 00000616
10:14:07.825 24404 explorer.exe  [WH] [taskbar-vertical] [1784:TaskListButton_UpdateVisualStates_Hook]: >
10:14:07.826 24404 explorer.exe  [WH] [taskbar-vertical] [1180:RepeatButton_Width_Hook]: >
10:14:07.826 24404 explorer.exe  [WH] [taskbar-vertical] [1784:TaskListButton_UpdateVisualStates_Hook]: >
10:14:07.826 24404 explorer.exe  [WH] [taskbar-vertical] [1180:RepeatButton_Width_Hook]: >
10:14:07.837 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:07.846 24404 explorer.exe  [WH] [taskbar-vertical] [427:TrayUI_MakeStuckRect_Hook]: >
10:14:07.846 24404 explorer.exe  [WH] [taskbar-vertical] [427:TrayUI_MakeStuckRect_Hook]: >
10:14:07.846 24404 explorer.exe  [WH] [taskbar-vertical] [427:TrayUI_MakeStuckRect_Hook]: >
10:14:07.846 24404 explorer.exe  [WH] [taskbar-vertical] [427:TrayUI_MakeStuckRect_Hook]: >
10:14:07.846 24404 explorer.exe  [WH] [taskbar-vertical] [333:TrayUI_GetMinSize_Hook]: >
10:14:07.846 24404 explorer.exe  [WH] [taskbar-vertical] [427:TrayUI_MakeStuckRect_Hook]: >
10:14:07.847 16576 SearchHost.exe  [WH] [taskbar-vertical] [2853:SetWindowPos_Hook]: 000801D8 00000616
10:14:09.109 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:09.175 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:09.177 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:09.177 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:09.180 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:09.197 24404 explorer.exe  [WH] [taskbar-vertical] [1784:TaskListButton_UpdateVisualStates_Hook]: >
10:14:09.197 24404 explorer.exe  [WH] [taskbar-vertical] [1180:RepeatButton_Width_Hook]: >
10:14:09.197 24404 explorer.exe  [WH] [taskbar-vertical] [1784:TaskListButton_UpdateVisualStates_Hook]: >
10:14:09.197 24404 explorer.exe  [WH] [taskbar-vertical] [1180:RepeatButton_Width_Hook]: >
10:14:10.621 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:10.621 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
10:14:10.647 24404 explorer.exe  [WH] [taskbar-vertical] [1864:ExperienceToggleButton_UpdateVisualStates_Hook]: >
```

**Comment by vikrend** [comment]
Hey! I face this bug as well. Can it be fixed? Really love the vertical taskbar, but this bug ruins the experience

**Comment by m417z** [comment]
I just released version 1.3.3 with a new start menu positioning method, and I believe that this issue is now fixed. Please try the new version and let me know if you encounter any issues.

**Comment by vikrend** [comment]
Hey! I've updated and it didn't fix the issue. But previously I used this mod, named "Taskbar Disappearing Icon Fix for Windows 11" and it fixed icons, but now it doesn't. The icons don't disappear - they get mispositioned and are not visible if the panel isn't wide enough

![Image](https://github.com/user-attachments/assets/a372a780-eb1e-43d4-915b-38b332a219b4)

**Comment by m417z** [comment]
@vikrend regarding the start menu issue, that's surprising, since it's now handled differently. Just to make sure, did you try restarting explorer.exe after the update? If not, please try it to make sure it's not related to some leftover state from the previous version of the mod.

Regarding the shifted icons, I've never seen this problem. If it doesn't get fixed after the restart, please create a new issue, thanks.

**Comment by vikrend** [comment]
Sorry, I've replied about another issue, with the icons :). The start menu is now fixed, thank you

**Comment by badigel** [comment]
I'm also having the shifted icons problem.

**Comment by m417z** [comment]
@badigel this issue is about the start menu location. Please create a new issue. Try to provide steps to reproduce the issue.

**Comment by Jerrk** [comment]
I'm running [Vertical Taskbar for Windows 11] and [Primary taskbar on secondary monitor].

clicking the windows start menu icon has no issues and opens the start menu on the correct monitor and location.

Pressing the windows key however will open the start menu on the **primary monitor** following the "Taskbar location on **secondary** monitors" setting in the [Vertical Taskbar for Windows 11] settings

not a huge deal since i don't often use the windows key but i though i'd mention it.

**Comment by m417z** [comment]
@Jerrk that sounds similar to this issue: https://github.com/ramensoftware/windhawk-mods/issues/1387.
