### ISSUE TITLE
[Taskbar Height and Icon Size] Not working after updating Windows to 10.0.26120.3380 (KB5053660)

### ISSUE THREAD

**Issue by AbdullahMRiad** [ramensoftware/windhawk-mods#1646]
The mod used to work perfectly fine before the update. Now it looks like this:

![Image](https://github.com/user-attachments/assets/3cdba39d-e324-4b63-9b54-a8d1ef3cea40)

(it's that tiny bit at the bottom)

The buttons are working but I can't obviously use it like that. I'd be happy to provide any further info required.

**Comment by longo2525** [comment]
I'm waiting for this to be fixed as well, please!

**Comment by LUKISO2** [comment]
For me only "Icon size" is not working leading to weird behavior when I make the "Taskbar height" smaller:

![Image](https://github.com/user-attachments/assets/0b8f59f1-c5c6-4606-966c-e9db8eb315a8)

**Comment by MNLierman** [comment]
For me, the taskbar is working completely fine, but when clicking on the overflow `. . .` button, Explorer crashes. Since this doesn't match what's already been reported, [I created a new issue here](https://github.com/ramensoftware/windhawk-mods/issues/1649), but I'm just curious if the `. . .` overflow button crashes for anyone else too?

**Comment by longo2525** [comment]
My overflow button crashed and the taskbar buttons not aligned to the center of the bar as well.

**Comment by godofhellwar** [comment]
The application breaks on Windows 11 canary version 27818.rs_prerelease.250314-1451 that just released. Prior to this release it was working just fine. Now the task bar height below 48 will cause it to display half the task bar as it starts to move the task bar down instead of adjusting the height. The icon size and space between icon no longer applies any changes.

**Comment by m417z** [comment]
Should be fixed in the recent update of the mod. After updating the mod, you might need to restart explorer to have the fix applied.

**Comment by AbdullahMRiad** [comment]
~~I updated the mod and restarted the explorer and it seems that the problem wasn't solved. I noticed that the taskbar height value in the mod settings shifts the taskbar vertically. Here are some examples:~~

<details>
<summary>Taskbar Height: 48</summary>

![Image](https://github.com/user-attachments/assets/857475be-0c95-4938-a328-acc404c8a0a2)

</details>

<details>
<summary>Taskbar Height: 72 (looks like the default)</summary>

![Image](https://github.com/user-attachments/assets/7a951e54-49c1-4be2-8eb3-eb183eba70d3)

</details>

<details>
<summary>Taskbar Height: 128</summary>

![Image](https://github.com/user-attachments/assets/862b46c1-524d-4710-8c29-705df76a0f34)

</details>

Edit (yes before I even posted the comment): I just solved the issue after setting the height to 128, restarting explorer.exe, then setting it to the height I want. I'm leaving it here for anyone who might face the same issue and might find it useful.
