### ISSUE TITLE
Taskbar Time and Date Modification stops working in Windows Insider Build 27818 (Canary)

### ISSUE THREAD

**Issue by NickDerry2023** [ramensoftware/windhawk-mods#1695]
This is a bug report from a Windows Insider on a new update coming from Microsoft that seems to change the way the taskbar time and date is rendered that affects mods with Windhawk, I suggest keeping an eye out as this update goes down the Windows Insider channels. Attached is a screenshot of said issue.

You can either include this build to be supported or wait and see if this issue is fixed in a later insider build.

This is for build 27818 (Canary)

![Image](https://github.com/user-attachments/assets/fe3d0d19-9457-4219-9188-f8ba371f5119)
![Image](https://github.com/user-attachments/assets/36c47a81-b4f6-4dd8-9e9b-9989c44cad4d)

**Comment by m417z** [comment]
Should be fixed in the recent update of the mod. After updating the mod, you might need to restart explorer to have the fix applied.

**Comment by emiliatheworst** [comment]
hello! sorry to bother, but i am on 26120 still and this tweak still doesnt seem to be working, even after updating the mod and restarting explorer

**Comment by m417z** [comment]
@emiliatheworst please create a new issue and attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.
