### ISSUE TITLE
[start-menu-all-apps] failure to open start menu after reboot

### ISSUE THREAD

**Issue by Bert-Proesmans** [ramensoftware/windhawk-mods#1852]
Having mod "start-menu-all-apps" enabled causes the start menu to not open.

1. Reboot and do not open start menu
2. Enable mod
3. Open start menu
4. Observe start menu not opening (BUG)

<details>

<summary>Mod log</summary>

```text
DbgViewMini v1.0.4
Listening for OutputDebugString messages...
# [bertp] Here I open the start menu
12:16:51.945 8976 StartMenuExperienceHost.exe  [WH] [start-menu-all-apps] [78:StartInnerFrameConstructorHook]: >
# [bertp] No more logging, but after clicking the start menu button multiple times the text below appears

12:24:26.734 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.26100
12:24:26.734 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.6.1
12:24:26.735 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod id: start-menu-all-apps
12:24:26.735 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.0.3
12:24:26.736 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FFCD0760000
12:24:26.736 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
12:24:26.739 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
12:24:26.742 1400 StartMenuExperienceHost.exe  [WH] [start-menu-all-apps] [90:Wh_ModInit]: >
12:24:26.751 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::HookSymbols
12:24:26.751 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Module: 00007FFCB0A90000
12:24:26.751 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Path: C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\StartMenu.dll
12:24:26.755 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Version: 2125.6006.0.0
12:24:26.756 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::HookSymbols]: Using symbol cache pdb_F841F7E6F1FA4B2C8F7B552A59F2F5431: 1#startmenu.dll#1740849186-3657728#public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::ShowAllApps(void)const #754676#public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::HideAllApps(void)const #755696#public: __cdecl winrt::StartMenu::implementation::StartInnerFrame::StartInnerFrame(struct winrt::WindowsUdk::UI::StartScreen::Implementation::DockedStartController const &,struct winrt::Windows::Foundation::IInspectable const &)#1445272
12:24:26.762 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: Found 00007FFCB0B483F4: public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::ShowAllApps(void)const 
12:24:26.763 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: To be hooked 00007FFCB0B487F0: public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::HideAllApps(void)const 
12:24:26.763 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: To be hooked 00007FFCB0BF0D98: public: __cdecl winrt::StartMenu::implementation::StartInnerFrame::StartInnerFrame(struct winrt::WindowsUdk::UI::StartScreen::Implementation::DockedStartController const &,struct winrt::Windows::Foundation::IInspectable const &)
12:24:26.764 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::ApplyPendingHooks]: Applying hooks
12:24:26.764 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
12:24:26.764 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFCB0B487F0
12:24:26.764 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFCD0761410
12:24:26.764 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
12:24:26.765 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
12:24:26.765 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFCB0BF0D98
12:24:26.765 1400 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFCD0761450
12:24:26.765 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
12:24:26.765 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::HookSymbols
12:24:26.766 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
12:24:26.766 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::AfterInit
12:24:26.766 1400 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::AfterInit
12:24:27.228 1400 StartMenuExperienceHost.exe  [WH] [start-menu-all-apps] [78:StartInnerFrameConstructorHook]: >
12:24:37.515 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
12:24:37.515 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.26100
12:24:37.515 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.6.1
12:24:37.515 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod id: start-menu-all-apps
12:24:37.515 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.0.3
12:24:37.520 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FFCE1BF0000
12:24:37.521 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
12:24:37.522 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
12:24:37.522 14316 StartMenuExperienceHost.exe  [WH] [start-menu-all-apps] [90:Wh_ModInit]: >
12:24:37.530 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::HookSymbols
12:24:37.530 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Module: 00007FFCB0A90000
12:24:37.532 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Path: C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\StartMenu.dll
12:24:37.532 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Version: 2125.6006.0.0
12:24:37.533 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::HookSymbols]: Using symbol cache pdb_F841F7E6F1FA4B2C8F7B552A59F2F5431: 1#startmenu.dll#1740849186-3657728#public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::ShowAllApps(void)const #754676#public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::HideAllApps(void)const #755696#public: __cdecl winrt::StartMenu::implementation::StartInnerFrame::StartInnerFrame(struct winrt::WindowsUdk::UI::StartScreen::Implementation::DockedStartController const &,struct winrt::Windows::Foundation::IInspectable const &)#1445272
12:24:37.534 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: Found 00007FFCB0B483F4: public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::ShowAllApps(void)const 
12:24:37.535 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: To be hooked 00007FFCB0B487F0: public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::HideAllApps(void)const 
12:24:37.535 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: To be hooked 00007FFCB0BF0D98: public: __cdecl winrt::StartMenu::implementation::StartInnerFrame::StartInnerFrame(struct winrt::WindowsUdk::UI::StartScreen::Implementation::DockedStartController const &,struct winrt::Windows::Foundation::IInspectable const &)
12:24:37.536 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::ApplyPendingHooks]: Applying hooks
12:24:37.536 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
12:24:37.537 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFCB0B487F0
12:24:37.537 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFCE1BF1410
12:24:37.537 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
12:24:37.537 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
12:24:37.538 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFCB0BF0D98
12:24:37.538 14316 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFCE1BF1450
12:24:37.538 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
12:24:37.538 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::HookSymbols
12:24:37.539 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
12:24:37.541 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::AfterInit
12:24:37.541 14316 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::AfterInit
12:24:37.980 14316 StartMenuExperienceHost.exe  [WH] [start-menu-all-apps] [78:StartInnerFrameConstructorHook]: >
```

</details>

Expected behaviour is for the start menu to open normally the first time. Within the same session, all subsequent attempts at opening the start menu directly opens the "all apps" section.

Windhawk v1.6.1
start-menu-all-apps v1.0.3
Win 11 v24H2 (26100.3775)

Workaround;
 
1. Disable mod
2. Open start menu
3. Re-enable mod

This returns to expected behaviour until system restart.
I keep the mod disabled until a fix arrives.

The above workaround makes me think some start menu initialisation phases shifted.

**Comment by m417z** [comment]
Fixed in version 1.0.4.

**Comment by m417z** [comment]
Actually, I'm not sure it'll fix it for you. The fix is for 26100.3915, and you're using 26100.3775. I'm looking at it, but I might give up if it becomes too consuming and if the fix in 1.0.4 works for newer versions.

**Comment by Bert-Proesmans** [comment]
hey, thanks for a quick fix!
I tested the updated code with my current windows version and the problem is not solved. That cumulative update you reference is queued so I might as well just go ahead and install it now. Then this issue can be closed.

<details>

<summary>Module logs</summary>

```text
DbgViewMini v1.0.4
Listening for OutputDebugString messages...
22:23:27.640 1776 StartMenuExperienceHost.exe  [WH] [start-menu-all-apps] [66:StartInnerFrameConstructor_Hook]: >
22:24:30.479 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::LoadedMod
22:24:30.488 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Windows 10.0.26100
22:24:30.489 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Windhawk v1.6.1
22:24:30.489 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod id: start-menu-all-apps
22:24:30.489 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod version: 1.0.4
22:24:30.490 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::LoadedMod]: Mod base address: 00007FFDC2FA0000
22:24:30.490 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::LoadedMod
22:24:30.490 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::Initialize
22:24:30.491 4812 StartMenuExperienceHost.exe  [WH] [start-menu-all-apps] [108:Wh_ModInit]: >
22:24:30.500 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::HookSymbols
22:24:30.500 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Module: 00007FFD9CEE0000
22:24:30.500 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Path: C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\StartMenu.dll
22:24:30.501 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::CalculateHookSymbolsInitialParams]: Version: 2125.6006.0.0
22:24:30.501 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::HookSymbols]: Using symbol cache pdb_F841F7E6F1FA4B2C8F7B552A59F2F5431: 1#startmenu.dll#1740849186-3657728#public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::ShowAllApps(void)const #754676#public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::HideAllApps(void)const #755696#public: __cdecl winrt::StartMenu::implementation::StartInnerFrame::StartInnerFrame(struct winrt::WindowsUdk::UI::StartScreen::Implementation::DockedStartController const &,struct winrt::Windows::Foundation::IInspectable const &)#1445272#struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides __cdecl winrt::impl::as<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControlle
22:24:30.502 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: Found 00007FFD9CF983F4: public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::ShowAllApps(void)const 
22:24:30.503 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: To be hooked 00007FFD9CF987F0: public: __cdecl winrt::impl::consume_WindowsUdk_UI_StartScreen_Implementation_IDockedStartControllerOverrides<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides>::HideAllApps(void)const 
22:24:30.503 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::OnSymbolResolved]: To be hooked 00007FFD9D040D98: public: __cdecl winrt::StartMenu::implementation::StartInnerFrame::StartInnerFrame(struct winrt::WindowsUdk::UI::StartScreen::Implementation::DockedStartController const &,struct winrt::Windows::Foundation::IInspectable const &)
22:24:30.504 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::ResolveSymbolsFromCacheParts::<lambda_1>::operator ()]: Optional symbol doesn't exist (from cache)
22:24:30.504 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::ResolveSymbolsFromCacheParts::<lambda_1>::operator ()]:     struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides __cdecl winrt::impl::as<struct winrt::WindowsUdk::UI::StartScreen::Implementation::IDockedStartControllerOverrides,struct winrt::impl::abi<struct winrt::Windows::Foundation::IUnknown,void>::type,0>(struct winrt::impl::abi<struct winrt::Windows::Foundation::IUnknown,void>::type *)
22:24:30.505 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::HookSymbolsSession::ApplyPendingHooks]: Applying hooks
22:24:30.505 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
22:24:30.505 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFD9CF987F0
22:24:30.506 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFDC2FA1360
22:24:30.506 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
22:24:30.506 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::SetFunctionHook
22:24:30.506 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Target: 00007FFD9D040D98
22:24:30.506 4812 StartMenuExperienceHost.exe  [WH] [LoadedMod::SetFunctionHook]: Hook: 00007FFDC2FA13A0
22:24:30.506 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::SetFunctionHook
22:24:30.507 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::HookSymbols
22:24:30.507 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::Initialize
22:24:30.508 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::ModDebugLoggingScope]: >>> Entering LoadedMod::AfterInit
22:24:30.508 4812 StartMenuExperienceHost.exe  [WH] [`anonymous-namespace'::ModDebugLoggingScope::~ModDebugLoggingScope]: <<< Exiting LoadedMod::AfterInit
22:24:30.984 4812 StartMenuExperienceHost.exe  [WH] [start-menu-all-apps] [66:StartInnerFrameConstructor_Hook]: >
```

</details>

**Comment by Bert-Proesmans** [comment]
Works good and fast on win v26100.3915
Thanks!
