### ISSUE TITLE
[Primary taskbar on secondary monitor] Taskbar alignment not saving

### ISSUE THREAD

**Issue by Nekoniria** [ramensoftware/windhawk-mods#2342]
When I enable this mod, "Taskbar alignment" in the taskbar settings doesn't save. In the settings I have it set to "Left" but when I click start it shows up in the Center. This can be fixed from changing the setting to "Center" then back to "Left", but on restart it goes back to opening to Center, while the setting never changes. In the registry editor it is also set at "0" which is Left and still with the same problems. 

@m417z

**Comment by m417z** [comment]
> If you're unable to reproduce the problem, I don't know what else to add.

Yeah, that's challenging to investigate such a problem without reproduction steps. If you can think of reproduction steps, let me know.

Maybe an obvious question, but: when the mod is disabled, there's no such issue, right?

**Comment by m417z** [comment]
> These are my monitor settings, it is set to monitor 1.

> My main display is set to monitor 1

Are these your previous settings, or did you change them for testing? Setting the monitor to the primary monitor means that the mod does nothing, since the primary taskbar is already on the primary monitor by default, even without the mod.

**Comment by m417z** [comment]
So if I understand correctly, the monitor numbers that the mod uses don't match the numbers on your first screenshot?

Let me know if I understand correctly:

Your primary monitor is monitor 1 on the screenshot.
Your secondary monitor is monitor 2 on the screenshot.

<img width="538" height="187" alt="Image" src="https://github.com/user-attachments/assets/cdb5340e-630c-4f04-95b7-a7940ffca124" />

If your mod settings are monitor=1, the primary taskbar moves to monitor 2 from the screenshot.
If your mod settings are monitor=2, the primary taskbar stays on monitor 1 from the screenshot (as if the mod is disabled).

Is that right?

**Comment by m417z** [comment]
I made some other experiments and I wasn't able to reproduce it. I saw some other weird behavior after changing my secondary monitor to be the primary monitor, such as the mod not always working. I tested it on a VM, maybe that's related too.

I'll keep an eye on this and other related issues, but for now, I don't have a way to fix it, and I don't plan on investing more time on it.

**Comment by Herysia** [comment]
Hey, I recently installed this mod because it's exactly the behavior I wanted for my oled as well. But I'm getting the same issue described in the thread.
- My primary monitor is my oled monitor, labelled 1.
- In the mod, I selected monitor 2 to hold the primary taskbar
- In windows I have: 
    - Taskbar LEFT
    - Taskbar on primary monitor only

<img width="599" height="235" alt="Image" src="https://github.com/user-attachments/assets/d4eb3f96-e10c-4fa4-915e-4ace6c6c060a" />

When I open the start menu it is centred until I change taskbar alignment to centre then left again.
And it does it again after each system restart.

I also tried enabling "show my taskbar on all displays" in windows settings, and if enabled, the start menu is opening correctly (on the left).
So I think the missing step for repro is to disable "show my taskbar on all displays". I also don't have auto hide, if that matters.

Let me know if I can provide any extra information

**Comment by m417z** [comment]
@Herysia thanks, the info helped. Hopefully fixed in Primary taskbar on secondary monitor v1.2.1. If not, let me know and I'll reopen the issue.

**Comment by Herysia** [comment]
Hi @m417z , Thanks for looking into this!

I tried v1.2.1, and unfortunately it doesn't seem to fix it for me. I'll try to share more info if you ever look into this again.

I noticed it happen again after each restart, and multiple things seems to fix it until the next restart (including changing taskbar alignment, enabling search icon, or re-enabling the mod)
This makes me think of an initialization failure

Meanwhile I'll keep using this version to see if it gets any better after some boot time (I only tried <30mn after boot currently)

Here is my windows taskbar settings:

<img width="885" height="1301" alt="Image" src="https://github.com/user-attachments/assets/7003588f-6be3-4976-9465-903dbe330c38" />
