### ISSUE TITLE
[Taskbar Labels for Windows 11] Badges are not possitioned correctly

### ISSUE THREAD

**Issue by remyblok** [ramensoftware/windhawk-mods#58]
I've installed The Taskbar Labels mod. When the taskbar item has badges they are not positioned correctly. For example in the following screenshot you see the red icon in Teams and the email icon in Outlook that are positioned in the middle in stead of the left corner of the icon.

![image](https://user-images.githubusercontent.com/12459155/200788363-3ead432b-439b-4537-a637-05fc452c9730.png)

**Comment by m417z** [comment]
Fixed in version 1.1 of the Taskbar Labels for Windows 11 mod. More details about the new version:
https://ramensoftware.com/windhawk-mod-update-taskbar-labels-for-windows-11

**Comment by Tellinq** [comment]
![image](https://user-images.githubusercontent.com/59412384/228983471-89d1602f-1bbb-4903-8c4b-df46aa92cf8c.png)

While this has mostly been fixed for me, I still have this occurring on Phone Link and Microsoft Teams.

**Comment by m417z** [comment]
@Tellinq This was fixed in version 1.1.2 (https://github.com/ramensoftware/windhawk-mods/issues/152).
